[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.19'
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2

[profile.lite]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.19'
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 0

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
amoy = "https://rpc-amoy.polygon.technology"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/" }
amoy = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/" }

